"""migração automática

Revision ID: 93b03a531c5a
Revises: 
Create Date: 2025-04-01 23:20:45.915289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b03a531c5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores_tipos',
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_materiais.id'], )
    )
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'tipos_materiais', ['tipo_id'], ['id'])

    op.drop_table('fornecedores_tipos')
    # ### end Alembic commands ###
